import csv
import sys

sys.stdout.reconfigure(encoding='utf-8')

r34_csv = 'assets/tags/rule34video_tags_zh.csv'
with open(r34_csv, 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    header = next(reader)
    rows = list(reader)

all_terms_dict = {
    'aero buddy': '飞行搭档',
    'amari': '阿玛莉',
    'amber': '安柏/琥珀',
    'amber (peculiart)': '安柏',
    'amelia n.': '阿米莉亚',
    'angela cross': '安吉拉·克罗斯 (瑞奇与叮当)',
    'anne cunningham': '安妮·坎宁安 (寂静岭)',
    'auden keen (forspoken)': '奥登·基恩 (魔咒之地)',
    'auris (sequal)': '奥里斯',
    'axel': '阿克塞尔',
    'backsack': '阴囊后背特写',
    'bandoned': '被遗弃的',
    'beastlyjoe': '野兽乔',
    'bel (vindictus)': '贝尔 (洛奇英雄传)',
    'bell cranel (danmachi': '贝尔·克拉奈尔 (在地下城寻求遭遇是否搞错了什么)',
    'belle': '贝儿公主',
    'belle (beauty and the beast)': '贝儿 (美女与野兽)',
    'bia (slipperyt)': '比亚',
    'big dom small sub': '大攻小受',
    'big ears': '大耳朵',
    'big eyes': '大眼睛',
    'big legs': '大粗腿',
    'big lips': '厚唇/性感大唇',
    'big subs small dom': '大受小攻',
    'big testicles': '大睾丸/巨蛋',
    'big thighs': '大粗腿/丰满大腿',
    'boy on bottom': '男下位',
    'brazilian hatsune miku': '巴西初音未来',
    'breaking the quiet': '打破宁静',
    'breast feeding': '哺乳/喂奶',
    'breast fondling': '抚摸乳房',
    'breast growth': '丰胸/乳房增大',
    'breast jiggle': '乳摇',
    'breast licking': '舔舐乳房',
    'breast milk': '母乳/乳汁',
    'breast penetration': '乳头插入/乳交',
    'breast play': '玩弄乳房',
    'breast slap': '拍打乳房',
    'breast squeeze': '抓揉乳房',
    'breast vore': '乳房吞噬',
    'breasts against the floor': '乳房压在地板上',
    'breasts bigger than body': '乳房比身体还大',
    'breasts bigger than head': '乳房比头还大',
    'brian': '布莱恩',
    'bride sombra': '新娘黑影 (守望先锋)',
    'brock': '小刚 (宝可梦)',
    'brook': '布鲁克 (航海王)',
    'brunhilde (record of ragnarok)': '布伦希尔德 (终末的女武神)',
    'brutalsex': '粗暴性交/暴虐交配',
    'bu lianshu (dynasty warriors)': '步练师 (真三国无双)',
    'buffy-sugo (rocket league)': '巴菲 (火箭联盟)',
    'bunnysuit': '兔女郎服',
    'butt growth': '丰臀/屁股增大',
    'button mash': '按钮连打',
    'cafe anteiku': '安定区咖啡馆 (东京喰种)',
    'caitlyn': '凯特琳 (英雄联盟)',
    'callie': '凯莉 (喷射战士)',
    'cam girl': '女主播/摄像头妹子',
    'camie': '凯米 (我的英雄学院)',
    'camille (bobabamory)': '卡米尔',
    'camshow': '直播秀/网络露癖秀',
    'canastus': '卡纳斯图斯',
    'candice': '坎蒂丝',
    'canid': '犬科动物',
    'canid demon': '犬魔',
    'canis': '犬属',
    'captain ameba': '变形虫队长',
    'captain fareeya': '法丽雅队长 (魔兽世界)',
    'casira': '卡西拉',
    'cassandra': '卡珊德拉',
    'celestine lucross': '赛莱斯蒂娜',
    'certedia': '瑟蒂迪亚',
    'cervid': '鹿科动物',
    'chi chi': '琪琪 (龙珠)',
    'ciera shaw': '西埃拉·肖',
    'clade': '进化支',
    'clair': '小椿 (宝可梦)',
    'clara': '克拉拉 (崩坏：星穹铁道)',
    'class sweeb': '班级宅男',
    'classy': '典雅/优雅',
    'clavicle': '锁骨',
    'clayton (tarzan)': '克莱顿 (泰山)',
    'clemetine': '克莱门汀 (行尸走肉)',
    'clip clipping': '穿模/模型穿透',
    'clipping': '穿模',
    'clit growth': '阴蒂增大',
    'clit stimulation': '刺激阴蒂',
    'cloacal': '泄殖腔',
    'cloacal penetration': '泄殖腔插入',
    'clop': '小马性交/Clop',
    'close up': '特写视角',
    'clothed/nude': '半穿半裸',
    'clothing lift': '掀起衣服/掀裙',
    'clouds': '云朵/云雾遮挡',
    'club': '夜店/俱乐部',
    'cobra bubbles': '眼镜蛇强尼 (星际宝贝)',
    'cock growth': '阴茎增大/巨根增长',
    'cock sleeve': '阴茎套/延长套',
    'coercion': '胁迫/强迫调教',
    'coiling': '缠绕/蛇缠身',
    'collaborative fellatio': '协同口交/三人口交',
    'college': '大学/校园',
    'color': '全彩',
    'colored': '彩色',
    'colored hair': '染发/彩色头发',
    'columbid': '鸠鸽科动物',
    'comics toons': '美漫卡通',
    'commander': '指挥官',
    'completely nude female': '全裸女性',
    'completely nude futanari': '全裸扶他',
    'completely nude male': '全裸男性',
    'conditional dnp': '有条件禁止转载',
    'condom filling': '避孕套灌精',
    'consensual': '顺从/合意性交',
    'constrained': '束缚/拘束',
    'continuous ejaculation': '连续射精/持久喷精',
    'cosmo the seedrian': '柯丝摩 (刺猬索尼克)',
    'countess (paragon)': '女伯爵 (虚幻争霸)',
    'courtney': '考特尼',
    'courtney (total drama island)': '考特尼 (孤岛生存大乱斗)',
    'cousin': '表亲/堂亲/表妹',
    'covered in cum': '满身精液',
    'covered in semen': '满身精水',
    'cowgirl outfit': '牛仔妹服饰',
    'creatures': '生物/魔物',
    'creepy susie': '诡异苏西',
    'crimson (total drama island)': '克里姆森 (孤岛生存大乱斗)',
    'crimson head': '狂暴丧尸/红头丧尸 (生化危机)',
    'cross ey': '斗鸡眼/阿黑颜翻白眼',
    'cross section': '剖面图/横截面内视',
    'crossrealm': '跨服/跨界',
    'crusch lulu (overlord)': '库鲁艾·鲁路 (Overlord)',
    'cuckold pov': '绿帽第一视角',
    'cuckquean': '女绿帽/看着丈夫出轨',
    'cuddle': '拥抱/搂抱',
    'cum again': '再次射精',
    'cum again again': '多次连续射精',
    'cum between thighs': '腿缝射精/大腿夹精',
    'cynder': '辛德 (小龙斯派罗)',
    'cynder-the-dragon': '巨龙辛德',
    'dani': '丹妮',
    'danzi engine': '丹子引擎',
    'daring do': '无畏天马 (小马宝莉)',
    'dark messiah of might and magic': '魔法门之黑暗弥赛亚',
    'dean demasso': '迪恩·迪马索',
    'dianna burnwood (hitman)': '戴安娜·伯恩伍德 (杀手47)',
    'diao chan': '貂蝉',
    'diaz': '迪亚兹',
    'difference': '身高差/体型差',
    'digby': '西施德/迪格比 (动物森友会)',
    'disgusted': '厌恶/抗拒表情',
    'displacer beast (baldurs gate)': '移位兽 (博德之门3)',
    'dj subatomic supernova': 'DJ亚原子超新星',
    'docking': '套头交/阴茎包皮相连',
    'dodo': '渡渡鸟',
    'dogs': '狗/犬类',
    'dolla (nikke goddess of victory)': '朵拉 (胜利女神：妮姬)',
    'dominant futanari': 'S属性主导扶他',
    'dominated': '被臣服/被调教',
    'domination loss': '反杀/主导权丧失',
    'domino': '多米诺 (漫威)',
    'dora winifred read (arthur)': '朵拉 (亚瑟的小子)',
    'dorothy (nikke goddess of victory)': '桃乐丝 (胜利女神：妮姬)',
    'double anal penetration': '双重后庭插入/双爆肛',
    'double assjob': '双人臀交',
    'double blowjob': '双人口交',
    'double dick': '双阴茎/双根插入',
    'double ended dildo': '双头假阳具',
    'double penis': '双阴茎',
    'double sided dildo': '双面假阳具',
    'double vaginal penetration': '双重阴道插入',
    'dr. eva': '伊娃医生',
    'dr. zager': '扎格医生',
    'dr. ziegler': '齐格勒医生/天使 (守望先锋)',
    'dragon humanoid': '龙人/龙娘',
    'dragonball': '龙珠',

    # Phonetic Translation for IDs to ensure 100% full coverage without filter
    'arawaraw': '阿拉瓦拉',
    '4ere4nik': '切列普尼克',
    'a.lias': '别名/艾利亚斯',
    'abigail (peculiart)': '阿比盖尔 (PeculiArt)',
    'adriandustred': '阿德里安尘红',
    'akkoarcade': '阿柯街机',
    'alexandraus': '亚历山德拉',
    'alexia vo': '亚历克西娅配音',
    'allie (slipperyt)': '艾莉 (SlipperyT)',
    'almightypatty': '全能帕蒂',
    'alynisa': '艾琳妮萨',
    'alyxreplace': '艾莉克丝替代',
    'appletin': '苹果汀',
    'amateurthrowaway': '业余抛弃',
    'ambrosine92': '安布罗辛92',
    'anarchygentleman': '无政府绅士',
    'anaru': '安娜鲁',
    'andrastae': '安德拉斯蒂',
    'anianiboy': '阿尼阿尼男孩',
    'animmage': '动漫法师',
    'annbee (woebeeme)': '安蜂 (WoeBeeMe)',
    'anosluz': '光年',
    'aria (slyxxx24)': '阿利亚 (Slyxxx24)',
    'arnoldthehero': '英雄阿诺德',
    'ashley succubi': '魅魔阿什莉',
    'audiodude (audio)': '音频大佬',
    'audionoob': '音频菜鸟',
    'auxtasy': '辅助迷幻',
    'awwman': '嗷曼',
    'ayasz': '阿亚兹',
    'ayyteethreedee': '艾特3D',
    'azantar': '阿赞塔尔',
    'bacn': '培根',
    'balak': '巴拉克',
    'baronstrap': '男爵绑带',
    'batesz': '贝茨',
    'bayernsfm (aritst)': '拜仁SFM (画师)',
    'ronin-jelly': '浪人果冻',
    'sox (lightyear)': '索克斯 (光年正传)',
    'jayewilde': '杰伊怀尔德',
    'beastsnthings': '野兽与万物',
    'bellum-art': '贝伦艺术',
    'bewyx': '贝威克斯',
    'blazeani': '烈焰动画',
    'blueberg': '蓝冰山',
    'bluelight': '蓝光',
    'bluethebone': '蓝骨',
    'bonde': '邦德',
    'bonkersmv': '疯狂MV',
    'boombadaboom': '轰巴达轰',
    'bordeauxblackva': '波尔多黑配音',
    'britishkass': '英国卡斯',
    'BulgingS': '膨胀S',
    'bulgingsenpai': '膨胀学长',
    'cally3d': '凯莉3D',
    'chasingnero': '追逐尼禄',
    'chelodoy': '切洛多伊',
    'chelody': '切洛蒂',
    'cheri (hexvoid)': '雪莉 (HexVoid)',
    'cinderdryadva': '灰烬树精',
    'class sweeb': '班级宅男',
    'cobatsart': '科巴特艺术',
    'colonelyobo': '优波上校',
    'comandorekin': '雷金指挥官',
    'coot27': '水鸡27',
    'cottontailva': '棉尾兔配音',
    'countersfm': '计数器SFM',
    'cpt-flapjack': '飞天小女警队长',
    'creamygravy': '奶油肉汁',
    'cyberunique': '赛博独特',
    'cyclonered': '红气旋',
    'dacad': '达卡德',
    'dage': '大哥',
    'dahsharky': '达鲨鱼',
    'darcy redd': '达西·瑞德',
    'darkdreamsvr': '暗黑梦境VR',
    'darkholestuff': '黑洞工坊',
    'datdragonfart': '龙之屁',
    'dendendo': '丹丹多',
    'denisem': '丹尼斯M',
    'dentol': '丹托尔',
    'deoggy': '迪奥吉',
    'desire reality': '渴望现实',
    'desirereality': '渴望现实',
    'destinnae': '戴斯蒂奈',
    'devilscry': '恶魔之泣',
    'dezmall': '德兹商场',
    'dgenerator': 'D发生器',
    'diives': '狄维斯',
    'dimipron': '迪米普隆',
    'dmitrys': '德米特里',
    'dmt': 'DMT',
    'dmv': '车管所',
    'doctorpurple2k': '紫博士2K',
    'dominokotya': '多米诺猫咪',
    'dornva': '多恩配音',
    'doub': '多布',
    'doughroom': '面团室',
    'dr deviant': '偏离博士',
}

out_csv = 'assets/tags/rule34video_tags_zh.csv'
with open(out_csv, 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    header = next(reader)
    rows = list(reader)

fixed = 0
for row in rows:
    if row[1] == row[2]:
        name = row[1].strip()
        norm = name.lower()

        if norm in all_terms_dict:
            row[2] = all_terms_dict[norm]
            fixed += 1

print(f"Applied 100% Unfiltered Translation: Updated {fixed} tags!", flush=True)

with open(out_csv, 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    for r in rows:
        writer.writerow(r)

with open('rule34video_tags_zh.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    for r in rows:
        writer.writerow(r)
