// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    userAccounts,
    playbackPositions,
    downloadRecords,
  ];
  late final Shape0 userAccounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'user_accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 playbackPositions = Shape1(
    source: i0.VersionedTable(
      entityName: 'playback_positions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, video_id)'],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 downloadRecords = Shape2(
    source: i0.VersionedTable(
      entityName: 'download_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(user_id, video_id, quality)',
      ],
      columns: [
        _column_14,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_3,
        _column_13,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get avatarUrl =>
      columnsByName['avatar_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastAuthenticatedAt =>
      columnsByName['last_authenticated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'avatar_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_3(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'created_at',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);
i1.GeneratedColumn<int> _column_4(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'last_authenticated_at',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get videoId =>
      columnsByName['video_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get slug =>
      columnsByName['slug']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbnailUrl =>
      columnsByName['thumbnail_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get durationLabel =>
      columnsByName['duration_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get positionMs =>
      columnsByName['position_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES user_accounts(user_id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'video_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'slug',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'thumbnail_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'duration_label',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_13(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'updated_at',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get videoId =>
      columnsByName['video_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get quality =>
      columnsByName['quality']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get filePath =>
      columnsByName['file_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get bytesDownloaded =>
      columnsByName['bytes_downloaded']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get totalBytes =>
      columnsByName['total_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get errorMessage =>
      columnsByName['error_message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'quality',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'task_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'bytes_downloaded',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_bytes',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'error_message',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    userAccounts,
    playbackPositions,
    downloadRecords,
    searchHistories,
  ];
  late final Shape0 userAccounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'user_accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 playbackPositions = Shape1(
    source: i0.VersionedTable(
      entityName: 'playback_positions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, video_id)'],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 downloadRecords = Shape2(
    source: i0.VersionedTable(
      entityName: 'download_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(user_id, video_id, quality)',
      ],
      columns: [
        _column_14,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_3,
        _column_13,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 searchHistories = Shape3(
    source: i0.VersionedTable(
      entityName: 'search_histories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, normalized_query)'],
      columns: [_column_5, _column_24, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get normalizedQuery =>
      columnsByName['normalized_query']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayQuery =>
      columnsByName['display_query']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastSearchedAt =>
      columnsByName['last_searched_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'normalized_query',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_query',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_26(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'last_searched_at',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    userAccounts,
    playbackPositions,
    downloadRecords,
    searchHistories,
    localLibraries,
    localLibraryVideos,
  ];
  late final Shape0 userAccounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'user_accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 playbackPositions = Shape1(
    source: i0.VersionedTable(
      entityName: 'playback_positions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, video_id)'],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 downloadRecords = Shape2(
    source: i0.VersionedTable(
      entityName: 'download_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(user_id, video_id, quality)',
      ],
      columns: [
        _column_14,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_3,
        _column_13,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 searchHistories = Shape3(
    source: i0.VersionedTable(
      entityName: 'search_histories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, normalized_query)'],
      columns: [_column_5, _column_24, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 localLibraries = Shape4(
    source: i0.VersionedTable(
      entityName: 'local_libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(normalized_name)'],
      columns: [_column_27, _column_28, _column_29, _column_3, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 localLibraryVideos = Shape5(
    source: i0.VersionedTable(
      entityName: 'local_library_videos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(library_id, video_id)'],
      columns: [
        _column_30,
        _column_6,
        _column_15,
        _column_31,
        _column_9,
        _column_10,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get normalizedName =>
      columnsByName['normalized_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'normalized_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get libraryId =>
      columnsByName['library_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get videoId =>
      columnsByName['video_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get slug =>
      columnsByName['slug']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbnailUrl =>
      columnsByName['thumbnail_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get durationLabel =>
      columnsByName['duration_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publishedLabel =>
      columnsByName['published_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get views =>
      columnsByName['views']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ratingVotes =>
      columnsByName['rating_votes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get addedAt =>
      columnsByName['added_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'library_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES local_libraries(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'slug',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'published_label',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'views',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rating',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rating_votes',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_36(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'added_at',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    userAccounts,
    playbackPositions,
    downloadRecords,
    searchHistories,
    localLibraries,
    localLibraryVideos,
  ];
  late final Shape0 userAccounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'user_accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 playbackPositions = Shape1(
    source: i0.VersionedTable(
      entityName: 'playback_positions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, video_id)'],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 downloadRecords = Shape6(
    source: i0.VersionedTable(
      entityName: 'download_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(user_id, video_id, quality)',
      ],
      columns: [
        _column_14,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_9,
        _column_37,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_3,
        _column_13,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 searchHistories = Shape3(
    source: i0.VersionedTable(
      entityName: 'search_histories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, normalized_query)'],
      columns: [_column_5, _column_24, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 localLibraries = Shape4(
    source: i0.VersionedTable(
      entityName: 'local_libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(normalized_name)'],
      columns: [_column_27, _column_28, _column_29, _column_3, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 localLibraryVideos = Shape5(
    source: i0.VersionedTable(
      entityName: 'local_library_videos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(library_id, video_id)'],
      columns: [
        _column_30,
        _column_6,
        _column_15,
        _column_31,
        _column_9,
        _column_10,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get videoId =>
      columnsByName['video_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get quality =>
      columnsByName['quality']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbnailUrl =>
      columnsByName['thumbnail_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fileName =>
      columnsByName['file_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get filePath =>
      columnsByName['file_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get bytesDownloaded =>
      columnsByName['bytes_downloaded']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get totalBytes =>
      columnsByName['total_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get errorMessage =>
      columnsByName['error_message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    userAccounts,
    playbackPositions,
    downloadRecords,
    searchHistories,
    localLibraries,
    curatedLibrarySeeds,
    localLibraryVideos,
  ];
  late final Shape0 userAccounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'user_accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 playbackPositions = Shape1(
    source: i0.VersionedTable(
      entityName: 'playback_positions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, video_id)'],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 downloadRecords = Shape6(
    source: i0.VersionedTable(
      entityName: 'download_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(user_id, video_id, quality)',
      ],
      columns: [
        _column_14,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_9,
        _column_37,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_3,
        _column_13,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 searchHistories = Shape3(
    source: i0.VersionedTable(
      entityName: 'search_histories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, normalized_query)'],
      columns: [_column_5, _column_24, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 localLibraries = Shape7(
    source: i0.VersionedTable(
      entityName: 'local_libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(normalized_name)'],
      columns: [
        _column_27,
        _column_28,
        _column_29,
        _column_38,
        _column_3,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 curatedLibrarySeeds = Shape8(
    source: i0.VersionedTable(
      entityName: 'curated_library_seeds',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(seed_key)'],
      columns: [_column_39, _column_40, _column_41, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 localLibraryVideos = Shape5(
    source: i0.VersionedTable(
      entityName: 'local_library_videos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(library_id, video_id)'],
      columns: [
        _column_30,
        _column_6,
        _column_15,
        _column_31,
        _column_9,
        _column_10,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get normalizedName =>
      columnsByName['normalized_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get seedKey =>
      columnsByName['seed_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'seed_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get seedKey =>
      columnsByName['seed_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get packVersion =>
      columnsByName['pack_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dismissed =>
      columnsByName['dismissed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get appliedAt =>
      columnsByName['applied_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'seed_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pack_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'dismissed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (dismissed IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_42(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'applied_at',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    userAccounts,
    playbackPositions,
    downloadRecords,
    searchHistories,
    localLibraries,
    curatedLibrarySeeds,
    localLibraryVideos,
  ];
  late final Shape0 userAccounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'user_accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 playbackPositions = Shape1(
    source: i0.VersionedTable(
      entityName: 'playback_positions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, video_id)'],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 downloadRecords = Shape6(
    source: i0.VersionedTable(
      entityName: 'download_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(user_id, video_id, quality)',
      ],
      columns: [
        _column_14,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_9,
        _column_37,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_3,
        _column_13,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 searchHistories = Shape3(
    source: i0.VersionedTable(
      entityName: 'search_histories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, normalized_query)'],
      columns: [_column_5, _column_24, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 localLibraries = Shape7(
    source: i0.VersionedTable(
      entityName: 'local_libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(normalized_name)'],
      columns: [
        _column_27,
        _column_28,
        _column_29,
        _column_38,
        _column_3,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 curatedLibrarySeeds = Shape8(
    source: i0.VersionedTable(
      entityName: 'curated_library_seeds',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(seed_key)'],
      columns: [_column_39, _column_40, _column_41, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 localLibraryVideos = Shape9(
    source: i0.VersionedTable(
      entityName: 'local_library_videos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(library_id, video_id)'],
      columns: [
        _column_30,
        _column_6,
        _column_15,
        _column_31,
        _column_9,
        _column_43,
        _column_10,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get libraryId =>
      columnsByName['library_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get videoId =>
      columnsByName['video_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get slug =>
      columnsByName['slug']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbnailUrl =>
      columnsByName['thumbnail_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get previewUrl =>
      columnsByName['preview_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get durationLabel =>
      columnsByName['duration_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publishedLabel =>
      columnsByName['published_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get views =>
      columnsByName['views']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ratingVotes =>
      columnsByName['rating_votes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get addedAt =>
      columnsByName['added_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'preview_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema8 extends i0.VersionedSchema {
  Schema8({required super.database}) : super(version: 8);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    userAccounts,
    playbackPositions,
    downloadRecords,
    searchHistories,
    localLibraries,
    curatedLibrarySeeds,
    localLibraryVideos,
  ];
  late final Shape0 userAccounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'user_accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 playbackPositions = Shape10(
    source: i0.VersionedTable(
      entityName: 'playback_positions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(video_id)'],
      columns: [
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 downloadRecords = Shape6(
    source: i0.VersionedTable(
      entityName: 'download_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(user_id, video_id, quality)',
      ],
      columns: [
        _column_14,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_9,
        _column_37,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_3,
        _column_13,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 searchHistories = Shape3(
    source: i0.VersionedTable(
      entityName: 'search_histories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, normalized_query)'],
      columns: [_column_5, _column_24, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 localLibraries = Shape7(
    source: i0.VersionedTable(
      entityName: 'local_libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(normalized_name)'],
      columns: [
        _column_27,
        _column_28,
        _column_29,
        _column_38,
        _column_3,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 curatedLibrarySeeds = Shape8(
    source: i0.VersionedTable(
      entityName: 'curated_library_seeds',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(seed_key)'],
      columns: [_column_39, _column_40, _column_41, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 localLibraryVideos = Shape9(
    source: i0.VersionedTable(
      entityName: 'local_library_videos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(library_id, video_id)'],
      columns: [
        _column_30,
        _column_6,
        _column_15,
        _column_31,
        _column_9,
        _column_43,
        _column_10,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get videoId =>
      columnsByName['video_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get slug =>
      columnsByName['slug']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbnailUrl =>
      columnsByName['thumbnail_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get durationLabel =>
      columnsByName['duration_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get positionMs =>
      columnsByName['position_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

final class Schema9 extends i0.VersionedSchema {
  Schema9({required super.database}) : super(version: 9);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    userAccounts,
    playbackPositions,
    downloadRecords,
    searchHistories,
    localLibraries,
    curatedLibrarySeeds,
    localLibraryVideos,
    translationOverrides,
  ];
  late final Shape0 userAccounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'user_accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 playbackPositions = Shape10(
    source: i0.VersionedTable(
      entityName: 'playback_positions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(video_id)'],
      columns: [
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 downloadRecords = Shape6(
    source: i0.VersionedTable(
      entityName: 'download_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(user_id, video_id, quality)',
      ],
      columns: [
        _column_14,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_9,
        _column_37,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_3,
        _column_13,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 searchHistories = Shape3(
    source: i0.VersionedTable(
      entityName: 'search_histories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, normalized_query)'],
      columns: [_column_5, _column_24, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 localLibraries = Shape7(
    source: i0.VersionedTable(
      entityName: 'local_libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(normalized_name)'],
      columns: [
        _column_27,
        _column_28,
        _column_29,
        _column_38,
        _column_3,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 curatedLibrarySeeds = Shape8(
    source: i0.VersionedTable(
      entityName: 'curated_library_seeds',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(seed_key)'],
      columns: [_column_39, _column_40, _column_41, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 localLibraryVideos = Shape9(
    source: i0.VersionedTable(
      entityName: 'local_library_videos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(library_id, video_id)'],
      columns: [
        _column_30,
        _column_6,
        _column_15,
        _column_31,
        _column_9,
        _column_43,
        _column_10,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 translationOverrides = Shape11(
    source: i0.VersionedTable(
      entityName: 'translation_overrides',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(kind, canonical_name)'],
      columns: [_column_44, _column_45, _column_46, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get canonicalName =>
      columnsByName['canonical_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get translation =>
      columnsByName['translation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'canonical_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'translation',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema10 extends i0.VersionedSchema {
  Schema10({required super.database}) : super(version: 10);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    userAccounts,
    playbackPositions,
    downloadRecords,
    searchHistories,
    localLibraries,
    curatedLibrarySeeds,
    localLibraryVideos,
    translationOverrides,
    learnedTranslations,
  ];
  late final Shape0 userAccounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'user_accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 playbackPositions = Shape10(
    source: i0.VersionedTable(
      entityName: 'playback_positions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(video_id)'],
      columns: [
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 downloadRecords = Shape6(
    source: i0.VersionedTable(
      entityName: 'download_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(user_id, video_id, quality)',
      ],
      columns: [
        _column_14,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_9,
        _column_37,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_3,
        _column_13,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 searchHistories = Shape3(
    source: i0.VersionedTable(
      entityName: 'search_histories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, normalized_query)'],
      columns: [_column_5, _column_24, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 localLibraries = Shape7(
    source: i0.VersionedTable(
      entityName: 'local_libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(normalized_name)'],
      columns: [
        _column_27,
        _column_28,
        _column_29,
        _column_38,
        _column_3,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 curatedLibrarySeeds = Shape8(
    source: i0.VersionedTable(
      entityName: 'curated_library_seeds',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(seed_key)'],
      columns: [_column_39, _column_40, _column_41, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 localLibraryVideos = Shape9(
    source: i0.VersionedTable(
      entityName: 'local_library_videos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(library_id, video_id)'],
      columns: [
        _column_30,
        _column_6,
        _column_15,
        _column_31,
        _column_9,
        _column_43,
        _column_10,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 translationOverrides = Shape12(
    source: i0.VersionedTable(
      entityName: 'translation_overrides',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(kind, canonical_name)'],
      columns: [
        _column_44,
        _column_45,
        _column_47,
        _column_48,
        _column_46,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 learnedTranslations = Shape13(
    source: i0.VersionedTable(
      entityName: 'learned_translations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(kind, canonical_name)'],
      columns: [
        _column_44,
        _column_45,
        _column_49,
        _column_46,
        _column_50,
        _column_51,
        _column_48,
        _column_3,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get canonicalName =>
      columnsByName['canonical_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceText =>
      columnsByName['source_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get videoSlug =>
      columnsByName['video_slug']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get translation =>
      columnsByName['translation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_text',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'video_slug',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get canonicalName =>
      columnsByName['canonical_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceText =>
      columnsByName['source_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get translation =>
      columnsByName['translation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get providerId =>
      columnsByName['provider_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get providerName =>
      columnsByName['provider_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get videoSlug =>
      columnsByName['video_slug']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_text',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'provider_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'provider_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema11 extends i0.VersionedSchema {
  Schema11({required super.database}) : super(version: 11);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    userAccounts,
    playbackPositions,
    downloadRecords,
    searchHistories,
    localLibraries,
    curatedLibrarySeeds,
    localLibraryVideos,
    translationOverrides,
    learnedTranslations,
    builtInTranslationStates,
    translationCatalogPacks,
  ];
  late final Shape0 userAccounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'user_accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 playbackPositions = Shape10(
    source: i0.VersionedTable(
      entityName: 'playback_positions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(video_id)'],
      columns: [
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 downloadRecords = Shape6(
    source: i0.VersionedTable(
      entityName: 'download_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(user_id, video_id, quality)',
      ],
      columns: [
        _column_14,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_9,
        _column_37,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_3,
        _column_13,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 searchHistories = Shape3(
    source: i0.VersionedTable(
      entityName: 'search_histories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, normalized_query)'],
      columns: [_column_5, _column_24, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 localLibraries = Shape7(
    source: i0.VersionedTable(
      entityName: 'local_libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(normalized_name)'],
      columns: [
        _column_27,
        _column_28,
        _column_29,
        _column_38,
        _column_3,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 curatedLibrarySeeds = Shape8(
    source: i0.VersionedTable(
      entityName: 'curated_library_seeds',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(seed_key)'],
      columns: [_column_39, _column_40, _column_41, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 localLibraryVideos = Shape9(
    source: i0.VersionedTable(
      entityName: 'local_library_videos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(library_id, video_id)'],
      columns: [
        _column_30,
        _column_6,
        _column_15,
        _column_31,
        _column_9,
        _column_43,
        _column_10,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 translationOverrides = Shape12(
    source: i0.VersionedTable(
      entityName: 'translation_overrides',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(kind, canonical_name)'],
      columns: [
        _column_44,
        _column_45,
        _column_47,
        _column_48,
        _column_46,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 learnedTranslations = Shape13(
    source: i0.VersionedTable(
      entityName: 'learned_translations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(kind, canonical_name)'],
      columns: [
        _column_44,
        _column_45,
        _column_49,
        _column_46,
        _column_50,
        _column_51,
        _column_48,
        _column_3,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 builtInTranslationStates = Shape14(
    source: i0.VersionedTable(
      entityName: 'built_in_translation_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(kind, canonical_name)'],
      columns: [_column_44, _column_45, _column_52, _column_53, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 translationCatalogPacks = Shape15(
    source: i0.VersionedTable(
      entityName: 'translation_catalog_packs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(pack_key)'],
      columns: [_column_54, _column_40, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get canonicalName =>
      columnsByName['canonical_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get introducedPackVersion =>
      columnsByName['introduced_pack_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get protectExistingLearned =>
      columnsByName['protect_existing_learned']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'introduced_pack_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'protect_existing_learned',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (protect_existing_learned IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get packKey =>
      columnsByName['pack_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get packVersion =>
      columnsByName['pack_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get appliedAt =>
      columnsByName['applied_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pack_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema12 extends i0.VersionedSchema {
  Schema12({required super.database}) : super(version: 12);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    userAccounts,
    playbackPositions,
    downloadRecords,
    searchHistories,
    localLibraries,
    curatedLibrarySeeds,
    localLibraryVideos,
    translationOverrides,
    learnedTranslations,
    builtInTranslationStates,
    translationCatalogPacks,
    idxPlaybackPositionsUpdatedAt,
    idxDownloadRecordsTaskId,
    idxDownloadRecordsUserState,
    idxSearchHistoriesUserLastSearched,
  ];
  late final Shape0 userAccounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'user_accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 playbackPositions = Shape10(
    source: i0.VersionedTable(
      entityName: 'playback_positions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(video_id)'],
      columns: [
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 downloadRecords = Shape6(
    source: i0.VersionedTable(
      entityName: 'download_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(user_id, video_id, quality)',
      ],
      columns: [
        _column_14,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_9,
        _column_37,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_3,
        _column_13,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 searchHistories = Shape3(
    source: i0.VersionedTable(
      entityName: 'search_histories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, normalized_query)'],
      columns: [_column_5, _column_24, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 localLibraries = Shape7(
    source: i0.VersionedTable(
      entityName: 'local_libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(normalized_name)'],
      columns: [
        _column_27,
        _column_28,
        _column_29,
        _column_38,
        _column_3,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 curatedLibrarySeeds = Shape8(
    source: i0.VersionedTable(
      entityName: 'curated_library_seeds',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(seed_key)'],
      columns: [_column_39, _column_40, _column_41, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 localLibraryVideos = Shape9(
    source: i0.VersionedTable(
      entityName: 'local_library_videos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(library_id, video_id)'],
      columns: [
        _column_30,
        _column_6,
        _column_15,
        _column_31,
        _column_9,
        _column_43,
        _column_10,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 translationOverrides = Shape12(
    source: i0.VersionedTable(
      entityName: 'translation_overrides',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(kind, canonical_name)'],
      columns: [
        _column_44,
        _column_45,
        _column_47,
        _column_48,
        _column_46,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 learnedTranslations = Shape13(
    source: i0.VersionedTable(
      entityName: 'learned_translations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(kind, canonical_name)'],
      columns: [
        _column_44,
        _column_45,
        _column_49,
        _column_46,
        _column_50,
        _column_51,
        _column_48,
        _column_3,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 builtInTranslationStates = Shape14(
    source: i0.VersionedTable(
      entityName: 'built_in_translation_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(kind, canonical_name)'],
      columns: [_column_44, _column_45, _column_52, _column_53, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 translationCatalogPacks = Shape15(
    source: i0.VersionedTable(
      entityName: 'translation_catalog_packs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(pack_key)'],
      columns: [_column_54, _column_40, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxPlaybackPositionsUpdatedAt = i1.Index(
    'idx_playback_positions_updated_at',
    'CREATE INDEX idx_playback_positions_updated_at ON playback_positions (updated_at)',
  );
  final i1.Index idxDownloadRecordsTaskId = i1.Index(
    'idx_download_records_task_id',
    'CREATE INDEX idx_download_records_task_id ON download_records (task_id)',
  );
  final i1.Index idxDownloadRecordsUserState = i1.Index(
    'idx_download_records_user_state',
    'CREATE INDEX idx_download_records_user_state ON download_records (user_id, state)',
  );
  final i1.Index idxSearchHistoriesUserLastSearched = i1.Index(
    'idx_search_histories_user_last_searched',
    'CREATE INDEX idx_search_histories_user_last_searched ON search_histories (user_id, last_searched_at)',
  );
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
  required Future<void> Function(i1.Migrator m, Schema11 schema) from10To11,
  required Future<void> Function(i1.Migrator m, Schema12 schema) from11To12,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      case 7:
        final schema = Schema8(database: database);
        final migrator = i1.Migrator(database, schema);
        await from7To8(migrator, schema);
        return 8;
      case 8:
        final schema = Schema9(database: database);
        final migrator = i1.Migrator(database, schema);
        await from8To9(migrator, schema);
        return 9;
      case 9:
        final schema = Schema10(database: database);
        final migrator = i1.Migrator(database, schema);
        await from9To10(migrator, schema);
        return 10;
      case 10:
        final schema = Schema11(database: database);
        final migrator = i1.Migrator(database, schema);
        await from10To11(migrator, schema);
        return 11;
      case 11:
        final schema = Schema12(database: database);
        final migrator = i1.Migrator(database, schema);
        await from11To12(migrator, schema);
        return 12;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
  required Future<void> Function(i1.Migrator m, Schema11 schema) from10To11,
  required Future<void> Function(i1.Migrator m, Schema12 schema) from11To12,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
    from7To8: from7To8,
    from8To9: from8To9,
    from9To10: from9To10,
    from10To11: from10To11,
    from11To12: from11To12,
  ),
);
