// GENERATED CODE - DO NOT MODIFY BY HAND.
// dart format off
//
// 数据来源：Han1meViewer (https://github.com/daisukiKaffuChino/Han1meViewer)
// assets/search_options/*.json，Apache-2.0 许可，见 THIRD_PARTY_NOTICES.md。
// 运行 tool/generate_hanime_search_options.dart 重新生成。

/// Hanime1 搜索筛选选项（数据搬运自 Han1meViewer）。
final class HanimeSearchOption {
  const HanimeSearchOption({
    required this.searchKey,
    required this.zh,
    required this.en,
    required this.ja,
    required this.tw,
  });

  /// 发送给 hanime1.me 的原始参数值；为 null 时表示“全部/不传该参数”。
  final String? searchKey;
  final String zh;
  final String en;
  final String ja;
  final String tw;

  String displayName(String localeCode) =>
      hanimeSearchOptionDisplayName(this, localeCode);
}

/// Hanime1 搜索标签分组（数据搬运自 Han1meViewer）。
final class HanimeTagGroup {
  const HanimeTagGroup({
    required this.id,
    required this.zh,
    required this.en,
    required this.ja,
    required this.tw,
    required this.options,
  });

  final String id;
  final String zh;
  final String en;
  final String ja;
  final String tw;
  final List<HanimeSearchOption> options;

  String displayName(String localeCode) =>
      hanimeTagGroupDisplayName(this, localeCode);
}

const hanimeGenres = <HanimeSearchOption>[HanimeSearchOption(searchKey: "全部", zh: "全部", en: "All", ja: "すべて", tw: "全部"),
    HanimeSearchOption(searchKey: "裏番", zh: "里番", en: "Hentai", ja: "裏番", tw: "裏番"),
    HanimeSearchOption(searchKey: "泡麵番", zh: "泡面番", en: "Short Anime", ja: "ショートアニメ", tw: "泡麵番"),
    HanimeSearchOption(searchKey: "Motion Anime", zh: "Motion Anime", en: "Motion Anime", ja: "モーションアニメ", tw: "Motion Anime"),
    HanimeSearchOption(searchKey: "3DCG", zh: "3D动画", en: "3D Animation", ja: "3Dアニメ", tw: "3D動畫"),
    HanimeSearchOption(searchKey: "2.5D", zh: "2.5D", en: "2.5D", ja: "2.5D", tw: "2.5D"),
    HanimeSearchOption(searchKey: "2D動畫", zh: "2D动画", en: "2D Animation", ja: "2Dアニメ", tw: "2D動畫"),
    HanimeSearchOption(searchKey: "AI生成", zh: "AI生成", en: "AI-Generated", ja: "AI生成", tw: "AI生成"),
    HanimeSearchOption(searchKey: "MMD", zh: "MMD", en: "MMD", ja: "MMD", tw: "MMD"),
    HanimeSearchOption(searchKey: "Cosplay", zh: "Cosplay", en: "Cosplay", ja: "コスプレ", tw: "Cosplay"),];

const hanimeSorts = <HanimeSearchOption>[HanimeSearchOption(searchKey: "最新上市", zh: "最新上市", en: "New Arrival", ja: "新着発売", tw: "最新上市"),
    HanimeSearchOption(searchKey: "最新上傳", zh: "最新上传", en: "New Upload", ja: "新着アップロード", tw: "最新上傳"),
    HanimeSearchOption(searchKey: "本日排行", zh: "本日排行", en: "Daily Ranking", ja: "本日ランキング", tw: "本日排行"),
    HanimeSearchOption(searchKey: "本週排行", zh: "本周排行", en: "Weekly Ranking", ja: "週間ランキング", tw: "本週排行"),
    HanimeSearchOption(searchKey: "本月排行", zh: "本月排行", en: "Monthly Ranking", ja: "月間ランキング", tw: "本月排行"),
    HanimeSearchOption(searchKey: "觀看次數", zh: "观看次数", en: "View Count", ja: "視聴回数", tw: "觀看次數"),
    HanimeSearchOption(searchKey: "讚好比例", zh: "点赞比例", en: "Like Ratio", ja: "高評価率", tw: "讚好比例"),
    HanimeSearchOption(searchKey: "他們在看", zh: "他们在看", en: "Trending", ja: "トレンド", tw: "他們在看"),
    HanimeSearchOption(searchKey: "時長最長", zh: "时长最长", en: "Longest duration", ja: "再生時間が長い", tw: "時長最長"),];

const hanimeDurations = <HanimeSearchOption>[HanimeSearchOption(searchKey: null, zh: "全部", en: "All", ja: "すべて", tw: "全部"),
    HanimeSearchOption(searchKey: "1 分鐘 +", zh: "1分钟以上", en: "More than 1 minute", ja: "1分以上", tw: "1分鐘以上"),
    HanimeSearchOption(searchKey: "5 分鐘 +", zh: "5分钟以上", en: "More than 5 minute", ja: "5分以上", tw: "5分鐘以上"),
    HanimeSearchOption(searchKey: "10 分鐘 +", zh: "10分钟以上", en: "More than 10 minutes", ja: "10分以上", tw: "10分鐘以上"),
    HanimeSearchOption(searchKey: "20 分鐘 +", zh: "20分钟以上", en: "More than 20 minutes", ja: "20分以上", tw: "20分鐘以上"),
    HanimeSearchOption(searchKey: "30 分鐘 +", zh: "30分钟以上", en: "More than 30 minutes", ja: "30分以上", tw: "30分鐘以上"),
    HanimeSearchOption(searchKey: "60 分鐘 +", zh: "60分钟以上", en: "More than 60 minutes", ja: "60分以上", tw: "60分鐘以上"),
    HanimeSearchOption(searchKey: "0 - 10 分鐘", zh: "0~10分钟", en: "0~10 minutes", ja: "0〜10分", tw: "0~10分鐘"),
    HanimeSearchOption(searchKey: "0 - 20 分鐘", zh: "0~20分钟", en: "0~20 minutes", ja: "0〜20分", tw: "0~20分鐘以上"),];

const hanimeReleaseDates = <HanimeSearchOption>[HanimeSearchOption(searchKey: null, zh: "全部", en: "All", ja: "すべて", tw: "全部"),
    HanimeSearchOption(searchKey: "過去 24 小時", zh: "过去24小时", en: "Last 24 hours", ja: "過去24時間", tw: "過去24小時"),
    HanimeSearchOption(searchKey: "過去 2 天", zh: "过去2天", en: "Last 2 days", ja: "過去2日", tw: "過去2天"),
    HanimeSearchOption(searchKey: "過去 1 週", zh: "过去1周", en: "Last week", ja: "過去1週間", tw: "過去1週"),
    HanimeSearchOption(searchKey: "過去 1 個月", zh: "过去1个月", en: "Last month", ja: "過去1か月", tw: "過去1個月"),
    HanimeSearchOption(searchKey: "過去 3 個月", zh: "过去3个月", en: "Last 3 months", ja: "過去3か月", tw: "過去3個月"),
    HanimeSearchOption(searchKey: "過去 1 年", zh: "过去1年", en: "Past year", ja: "過去1年", tw: "過去1年"),];

const hanimeBrands = <HanimeSearchOption>[HanimeSearchOption(searchKey: "妄想実現めでぃあ", zh: "妄想実現めでぃあ", en: "妄想実現めでぃあ", ja: "妄想実現めでぃあ", tw: "妄想実現めでぃあ"),
    HanimeSearchOption(searchKey: "メリー・ジェーン", zh: "メリー・ジェーン", en: "メリー・ジェーン", ja: "メリー・ジェーン", tw: "メリー・ジェーン"),
    HanimeSearchOption(searchKey: "ピンクパイナップル", zh: "ピンクパイナップル", en: "ピンクパイナップル", ja: "ピンクパイナップル", tw: "ピンクパイナップル"),
    HanimeSearchOption(searchKey: "ばにぃうぉ～か～", zh: "ばにぃうぉ～か～", en: "ばにぃうぉ～か～", ja: "ばにぃうぉ～か～", tw: "ばにぃうぉ～か～"),
    HanimeSearchOption(searchKey: "Queen Bee", zh: "Queen Bee", en: "Queen Bee", ja: "Queen Bee", tw: "Queen Bee"),
    HanimeSearchOption(searchKey: "PoRO", zh: "PoRO", en: "PoRO", ja: "PoRO", tw: "PoRO"),
    HanimeSearchOption(searchKey: "せるふぃっしゅ", zh: "せるふぃっしゅ", en: "せるふぃっしゅ", ja: "せるふぃっしゅ", tw: "せるふぃっしゅ"),
    HanimeSearchOption(searchKey: "鈴木みら乃", zh: "鈴木みら乃", en: "鈴木みら乃", ja: "鈴木みら乃", tw: "鈴木みら乃"),
    HanimeSearchOption(searchKey: "ショーテン", zh: "ショーテン", en: "ショーテン", ja: "ショーテン", tw: "ショーテン"),
    HanimeSearchOption(searchKey: "GOLD BEAR", zh: "GOLD BEAR", en: "GOLD BEAR", ja: "GOLD BEAR", tw: "GOLD BEAR"),
    HanimeSearchOption(searchKey: "ZIZ", zh: "ZIZ", en: "ZIZ", ja: "ZIZ", tw: "ZIZ"),
    HanimeSearchOption(searchKey: "EDGE", zh: "EDGE", en: "EDGE", ja: "EDGE", tw: "EDGE"),
    HanimeSearchOption(searchKey: "Collaboration Works", zh: "Collaboration Works", en: "Collaboration Works", ja: "Collaboration Works", tw: "Collaboration Works"),
    HanimeSearchOption(searchKey: "BOOTLEG", zh: "BOOTLEG", en: "BOOTLEG", ja: "BOOTLEG", tw: "BOOTLEG"),
    HanimeSearchOption(searchKey: "BOMB!CUTE!BOMB!", zh: "BOMB!CUTE!BOMB!", en: "BOMB!CUTE!BOMB!", ja: "BOMB!CUTE!BOMB!", tw: "BOMB!CUTE!BOMB!"),
    HanimeSearchOption(searchKey: "nur", zh: "nur", en: "nur", ja: "nur", tw: "nur"),
    HanimeSearchOption(searchKey: "あんてきぬすっ", zh: "あんてきぬすっ", en: "あんてきぬすっ", ja: "あんてきぬすっ", tw: "あんてきぬすっ"),
    HanimeSearchOption(searchKey: "魔人", zh: "魔人", en: "魔人", ja: "魔人", tw: "魔人"),
    HanimeSearchOption(searchKey: "ルネ", zh: "ルネ", en: "ルネ", ja: "ルネ", tw: "ルネ"),
    HanimeSearchOption(searchKey: "Princess Sugar", zh: "Princess Sugar", en: "Princess Sugar", ja: "Princess Sugar", tw: "Princess Sugar"),
    HanimeSearchOption(searchKey: "パシュミナ", zh: "パシュミナ", en: "パシュミナ", ja: "パシュミナ", tw: "パシュミナ"),
    HanimeSearchOption(searchKey: "WHITE BEAR", zh: "WHITE BEAR", en: "WHITE BEAR", ja: "WHITE BEAR", tw: "WHITE BEAR"),
    HanimeSearchOption(searchKey: "AniMan", zh: "AniMan", en: "AniMan", ja: "AniMan", tw: "AniMan"),
    HanimeSearchOption(searchKey: "chippai", zh: "chippai", en: "chippai", ja: "chippai", tw: "chippai"),
    HanimeSearchOption(searchKey: "トップマーシャル", zh: "トップマーシャル", en: "トップマーシャル", ja: "トップマーシャル", tw: "トップマーシャル"),
    HanimeSearchOption(searchKey: "erozuki", zh: "erozuki", en: "erozuki", ja: "erozuki", tw: "erozuki"),
    HanimeSearchOption(searchKey: "サークルトリビュート", zh: "サークルトリビュート", en: "サークルトリビュート", ja: "サークルトリビュート", tw: "サークルトリビュート"),
    HanimeSearchOption(searchKey: "spermation", zh: "spermation", en: "spermation", ja: "spermation", tw: "spermation"),
    HanimeSearchOption(searchKey: "Milky", zh: "Milky", en: "Milky", ja: "Milky", tw: "Milky"),
    HanimeSearchOption(searchKey: "King Bee", zh: "King Bee", en: "King Bee", ja: "King Bee", tw: "King Bee"),
    HanimeSearchOption(searchKey: "PashminaA", zh: "PashminaA", en: "PashminaA", ja: "PashminaA", tw: "PashminaA"),
    HanimeSearchOption(searchKey: "じゅうしぃまんご～", zh: "じゅうしぃまんご～", en: "じゅうしぃまんご～", ja: "じゅうしぃまんご～", tw: "じゅうしぃまんご～"),
    HanimeSearchOption(searchKey: "Hills", zh: "Hills", en: "Hills", ja: "Hills", tw: "Hills"),
    HanimeSearchOption(searchKey: "妄想専科", zh: "妄想専科", en: "妄想専科", ja: "妄想専科", tw: "妄想専科"),
    HanimeSearchOption(searchKey: "ディスカバリー", zh: "ディスカバリー", en: "ディスカバリー", ja: "ディスカバリー", tw: "ディスカバリー"),
    HanimeSearchOption(searchKey: "ひまじん", zh: "ひまじん", en: "ひまじん", ja: "ひまじん", tw: "ひまじん"),
    HanimeSearchOption(searchKey: "37℃", zh: "37℃", en: "37℃", ja: "37℃", tw: "37℃"),
    HanimeSearchOption(searchKey: "schoolzone", zh: "schoolzone", en: "schoolzone", ja: "schoolzone", tw: "schoolzone"),
    HanimeSearchOption(searchKey: "GREEN BUNNY", zh: "GREEN BUNNY", en: "GREEN BUNNY", ja: "GREEN BUNNY", tw: "GREEN BUNNY"),
    HanimeSearchOption(searchKey: "バニラ", zh: "バニラ", en: "バニラ", ja: "バニラ", tw: "バニラ"),
    HanimeSearchOption(searchKey: "L.", zh: "L.", en: "L.", ja: "L.", tw: "L."),
    HanimeSearchOption(searchKey: "PIXY", zh: "PIXY", en: "PIXY", ja: "PIXY", tw: "PIXY"),
    HanimeSearchOption(searchKey: "こっとんど～る", zh: "こっとんど～る", en: "こっとんど～る", ja: "こっとんど～る", tw: "こっとんど～る"),
    HanimeSearchOption(searchKey: "ANIMAC", zh: "ANIMAC", en: "ANIMAC", ja: "ANIMAC", tw: "ANIMAC"),
    HanimeSearchOption(searchKey: "Celeb", zh: "Celeb", en: "Celeb", ja: "Celeb", tw: "Celeb"),
    HanimeSearchOption(searchKey: "MOON ROCK", zh: "MOON ROCK", en: "MOON ROCK", ja: "MOON ROCK", tw: "MOON ROCK"),
    HanimeSearchOption(searchKey: "Dream", zh: "Dream", en: "Dream", ja: "Dream", tw: "Dream"),
    HanimeSearchOption(searchKey: "ミンク", zh: "ミンク", en: "ミンク", ja: "ミンク", tw: "ミンク"),
    HanimeSearchOption(searchKey: "オズ・インク", zh: "オズ・インク", en: "オズ・インク", ja: "オズ・インク", tw: "オズ・インク"),
    HanimeSearchOption(searchKey: "サン出版", zh: "サン出版", en: "サン出版", ja: "サン出版", tw: "サン出版"),
    HanimeSearchOption(searchKey: "ポニーキャニオン", zh: "ポニーキャニオン", en: "ポニーキャニオン", ja: "ポニーキャニオン", tw: "ポニーキャニオン"),
    HanimeSearchOption(searchKey: "わるきゅ～れ＋＋", zh: "わるきゅ～れ＋＋", en: "わるきゅ～れ＋＋", ja: "わるきゅ～れ＋＋", tw: "わるきゅ～れ＋＋"),
    HanimeSearchOption(searchKey: "株式会社虎の穴", zh: "株式会社虎の穴", en: "株式会社虎の穴", ja: "株式会社虎の穴", tw: "株式会社虎の穴"),
    HanimeSearchOption(searchKey: "エンゼルフィッシュ", zh: "エンゼルフィッシュ", en: "エンゼルフィッシュ", ja: "エンゼルフィッシュ", tw: "エンゼルフィッシュ"),
    HanimeSearchOption(searchKey: "UNION-CHO", zh: "UNION-CHO", en: "UNION-CHO", ja: "UNION-CHO", tw: "UNION-CHO"),
    HanimeSearchOption(searchKey: "TOHO", zh: "TOHO", en: "TOHO", ja: "TOHO", tw: "TOHO"),
    HanimeSearchOption(searchKey: "ミルクセーキ", zh: "ミルクセーキ", en: "ミルクセーキ", ja: "ミルクセーキ", tw: "ミルクセーキ"),
    HanimeSearchOption(searchKey: "2匹目のどぜう", zh: "2匹目のどぜう", en: "2匹目のどぜう", ja: "2匹目のどぜう", tw: "2匹目のどぜう"),
    HanimeSearchOption(searchKey: "じゅうしぃまんご～", zh: "じゅうしぃまんご～", en: "じゅうしぃまんご～", ja: "じゅうしぃまんご～", tw: "じゅうしぃまんご～"),
    HanimeSearchOption(searchKey: "ツクルノモリ", zh: "ツクルノモリ", en: "ツクルノモリ", ja: "ツクルノモリ", tw: "ツクルノモリ"),
    HanimeSearchOption(searchKey: "サークルトリビュート", zh: "サークルトリビュート", en: "サークルトリビュート", ja: "サークルトリビュート", tw: "サークルトリビュート"),
    HanimeSearchOption(searchKey: "トップマーシャル", zh: "トップマーシャル", en: "トップマーシャル", ja: "トップマーシャル", tw: "トップマーシャル"),
    HanimeSearchOption(searchKey: "彗星社", zh: "彗星社", en: "彗星社", ja: "彗星社", tw: "彗星社"),
    HanimeSearchOption(searchKey: "ナチュラルハイ", zh: "ナチュラルハイ", en: "ナチュラルハイ", ja: "ナチュラルハイ", tw: "ナチュラルハイ"),
    HanimeSearchOption(searchKey: "れもんは～と", zh: "れもんは～と", en: "れもんは～と", ja: "れもんは～と", tw: "れもんは～と"),];

const hanimeTagGroups = <HanimeTagGroup>[HanimeTagGroup(id: "video_attributes", zh: "影片属性", en: "Video Attributes", ja: "ビデオ属性", tw: "影片屬性", options: <HanimeSearchOption>[HanimeSearchOption(searchKey: "無碼", zh: "无码", en: "Uncensored", ja: "無修正", tw: "無碼"),
    HanimeSearchOption(searchKey: "AI解碼", zh: "AI解码", en: "AI Decoded", ja: "AIデコード", tw: "AI解碼"),
    HanimeSearchOption(searchKey: "中文字幕", zh: "中文字幕", en: "Chinese Subtitle", ja: "中国語字幕", tw: "中文字幕"),
    HanimeSearchOption(searchKey: "中文配音", zh: "中文配音", en: "Chinese dubbing", ja: "中国語吹き替え", tw: "中文配音"),
    HanimeSearchOption(searchKey: "同人作品", zh: "同人作品", en: "Fan Video", ja: "同人作品", tw: "同人作品"),
    HanimeSearchOption(searchKey: "斷面圖", zh: "断面图", en: "Cross-section", ja: "断面図", tw: "斷面圖"),
    HanimeSearchOption(searchKey: "ASMR", zh: "ASMR", en: "ASMR", ja: "ASMR", tw: "ASMR"),
    HanimeSearchOption(searchKey: "1080p", zh: "1080P", en: "1080P", ja: "1080p", tw: "1080P"),
    HanimeSearchOption(searchKey: "60FPS", zh: "60FPS", en: "60FPS", ja: "60FPS", tw: "60FPS"),]),
    HanimeTagGroup(id: "character_relationships", zh: "人物关系", en: "Character Relationships", ja: "キャラクター関係", tw: "人物關係", options: <HanimeSearchOption>[HanimeSearchOption(searchKey: "近親", zh: "近亲", en: "Incest", ja: "近親", tw: "近親"),
    HanimeSearchOption(searchKey: "姐", zh: "姐", en: "Elder Sister", ja: "姉", tw: "姐"),
    HanimeSearchOption(searchKey: "妹", zh: "妹", en: "Younger Sister", ja: "妹", tw: "妹"),
    HanimeSearchOption(searchKey: "母", zh: "母", en: "Mother", ja: "母", tw: "母"),
    HanimeSearchOption(searchKey: "女兒", zh: "女儿", en: "Daughter", ja: "娘", tw: "女兒"),
    HanimeSearchOption(searchKey: "師生", zh: "师生", en: "Teacher Student", ja: "教師と生徒", tw: "師生"),
    HanimeSearchOption(searchKey: "情侶", zh: "情侣", en: "Couple", ja: "カップル", tw: "情侶"),
    HanimeSearchOption(searchKey: "青梅竹馬", zh: "青梅竹马", en: "Childhood Friend", ja: "幼なじみ", tw: "青梅竹馬"),
    HanimeSearchOption(searchKey: "同事", zh: "同事", en: "Colleague", ja: "同僚", tw: "同事"),]),
    HanimeTagGroup(id: "characteristics", zh: "角色设定", en: "Characteristics", ja: "特性", tw: "角色設定", options: <HanimeSearchOption>[HanimeSearchOption(searchKey: "JK", zh: "JK", en: "JK", ja: "JK", tw: "JK"),
    HanimeSearchOption(searchKey: "處女", zh: "处女", en: "Virgin", ja: "処女", tw: "處女"),
    HanimeSearchOption(searchKey: "御姐", zh: "御姐", en: "Older Sister", ja: "お姉さん", tw: "御姐"),
    HanimeSearchOption(searchKey: "熟女", zh: "熟女", en: "MILF", ja: "熟女", tw: "熟女"),
    HanimeSearchOption(searchKey: "人妻", zh: "人妻", en: "Married Woman", ja: "人妻", tw: "人妻"),
    HanimeSearchOption(searchKey: "女教師", zh: "女教师", en: "Female Teacher", ja: "女教師", tw: "女教師"),
    HanimeSearchOption(searchKey: "男教師", zh: "男教师", en: "Male Teacher", ja: "男教師", tw: "男教師"),
    HanimeSearchOption(searchKey: "女醫生", zh: "女医生", en: "Female Doctor", ja: "女医", tw: "女醫生"),
    HanimeSearchOption(searchKey: "女病人", zh: "女病人", en: "Female Patient", ja: "女性患者", tw: "女病人"),
    HanimeSearchOption(searchKey: "護士", zh: "护士", en: "Nurse", ja: "看護師", tw: "護士"),
    HanimeSearchOption(searchKey: "OL", zh: "OL", en: "Office Lady", ja: "OL", tw: "OL"),
    HanimeSearchOption(searchKey: "女警", zh: "女警", en: "Policewoman", ja: "婦警", tw: "女警"),
    HanimeSearchOption(searchKey: "大小姐", zh: "大小姐", en: "Young Lady", ja: "お嬢様", tw: "大小姐"),
    HanimeSearchOption(searchKey: "偶像", zh: "偶像", en: "Idol", ja: "アイドル", tw: "偶像"),
    HanimeSearchOption(searchKey: "女僕", zh: "女仆", en: "Maid", ja: "メイド", tw: "女僕"),
    HanimeSearchOption(searchKey: "巫女", zh: "巫女", en: "Shrine Maiden", ja: "巫女", tw: "巫女"),
    HanimeSearchOption(searchKey: "魔女", zh: "魔女", en: "Witch", ja: "魔女", tw: "魔女"),
    HanimeSearchOption(searchKey: "修女", zh: "修女", en: "Nun", ja: "シスター", tw: "修女"),
    HanimeSearchOption(searchKey: "風俗娘", zh: "风俗娘", en: "Sex Worker", ja: "風俗嬢", tw: "風俗娘"),
    HanimeSearchOption(searchKey: "公主", zh: "公主", en: "Princess", ja: "姫", tw: "公主"),
    HanimeSearchOption(searchKey: "女忍者", zh: "女忍者", en: "Kunoichi", ja: "女忍者", tw: "女忍者"),
    HanimeSearchOption(searchKey: "女戰士", zh: "女战士", en: "Female Warrior", ja: "女戦士", tw: "女戰士"),
    HanimeSearchOption(searchKey: "女騎士", zh: "女骑士", en: "Female Knight", ja: "女騎士", tw: "女騎士"),
    HanimeSearchOption(searchKey: "魔法少女", zh: "魔法少女", en: "Magical Girl", ja: "魔法少女", tw: "魔法少女"),
    HanimeSearchOption(searchKey: "異種族", zh: "异种族", en: "Different Species", ja: "異種族", tw: "異種族"),
    HanimeSearchOption(searchKey: "天使", zh: "天使", en: "Angel", ja: "天使", tw: "天使"),
    HanimeSearchOption(searchKey: "妖精", zh: "妖精", en: "Fairy", ja: "妖精", tw: "妖精"),
    HanimeSearchOption(searchKey: "魔物娘", zh: "魔物娘", en: "Monster Girl", ja: "魔物娘", tw: "魔物娘"),
    HanimeSearchOption(searchKey: "魅魔", zh: "魅魔", en: "Succubus", ja: "サキュバス", tw: "魅魔"),
    HanimeSearchOption(searchKey: "吸血鬼", zh: "吸血鬼", en: "Vampire", ja: "吸血鬼", tw: "吸血鬼"),
    HanimeSearchOption(searchKey: "女鬼", zh: "女鬼", en: "Female Ghost", ja: "女幽霊", tw: "女鬼"),
    HanimeSearchOption(searchKey: "獸娘", zh: "兽娘", en: "Kemonomimi", ja: "獣娘", tw: "獸娘"),
    HanimeSearchOption(searchKey: "福瑞", zh: "Furry", en: "Furry", ja: "ファーリー", tw: "Furry"),
    HanimeSearchOption(searchKey: "乳牛", zh: "乳牛", en: "Cow Girl", ja: "乳牛", tw: "乳牛"),
    HanimeSearchOption(searchKey: "機械娘", zh: "机械娘", en: "Android Girl", ja: "メカ娘", tw: "機械娘"),
    HanimeSearchOption(searchKey: "碧池", zh: "碧池", en: "Bitch", ja: "ビッチ", tw: "碧池"),
    HanimeSearchOption(searchKey: "痴女", zh: "痴女", en: "Nymphomaniac", ja: "痴女", tw: "痴女"),
    HanimeSearchOption(searchKey: "雌小鬼", zh: "雌小鬼", en: "Cheeky Girl", ja: "メスガキ", tw: "雌小鬼"),
    HanimeSearchOption(searchKey: "不良少女", zh: "不良少女", en: "Delinquent Girl", ja: "不良少女", tw: "不良少女"),
    HanimeSearchOption(searchKey: "傲嬌", zh: "傲娇", en: "Tsundere", ja: "ツンデレ", tw: "傲嬌"),
    HanimeSearchOption(searchKey: "病嬌", zh: "病娇", en: "Yandere", ja: "ヤンデレ", tw: "病嬌"),
    HanimeSearchOption(searchKey: "無口", zh: "无口", en: "Quiet", ja: "無口", tw: "無口"),
    HanimeSearchOption(searchKey: "無表情", zh: "无表情", en: "Expressionless", ja: "無表情", tw: "無表情"),
    HanimeSearchOption(searchKey: "眼神死", zh: "眼神死", en: "Dead Eyes", ja: "死んだ目", tw: "眼神死"),
    HanimeSearchOption(searchKey: "正太", zh: "正太", en: "Shota", ja: "ショタ", tw: "正太"),
    HanimeSearchOption(searchKey: "偽娘", zh: "伪娘", en: "Crossdresser", ja: "男の娘", tw: "偽娘"),
    HanimeSearchOption(searchKey: "扶他", zh: "扶他", en: "Futanari", ja: "ふたなり", tw: "扶他"),]),
    HanimeTagGroup(id: "appearance_and_figure", zh: "外貌身材", en: "Appearance and Figure", ja: "外見と体格", tw: "外貌身材", options: <HanimeSearchOption>[HanimeSearchOption(searchKey: "短髮", zh: "短发", en: "Short Hair", ja: "ショートヘア", tw: "短髮"),
    HanimeSearchOption(searchKey: "馬尾", zh: "马尾", en: "Ponytail", ja: "ポニーテール", tw: "馬尾"),
    HanimeSearchOption(searchKey: "雙馬尾", zh: "双马尾", en: "Twin Tail", ja: "ツインテール", tw: "雙馬尾"),
    HanimeSearchOption(searchKey: "丸子頭", zh: "丸子头", en: "Hair bun", ja: "お団子ヘア", tw: "丸子頭"),
    HanimeSearchOption(searchKey: "巨乳", zh: "巨乳", en: "Big Breasts", ja: "巨乳", tw: "巨乳"),
    HanimeSearchOption(searchKey: "乳環", zh: "乳环", en: "Nipple Ring", ja: "ニップルピアス", tw: "乳環"),
    HanimeSearchOption(searchKey: "舌環", zh: "舌环", en: "Tongue Ring", ja: "舌ピアス", tw: "舌環"),
    HanimeSearchOption(searchKey: "貧乳", zh: "贫乳", en: "Small Breasts", ja: "貧乳", tw: "貧乳"),
    HanimeSearchOption(searchKey: "黑皮膚", zh: "黑皮肤", en: "Dark Skin", ja: "褐色肌", tw: "黑皮膚"),
    HanimeSearchOption(searchKey: "曬痕", zh: "晒痕", en: "Tanlines", ja: "日焼け跡", tw: "曬痕"),
    HanimeSearchOption(searchKey: "眼鏡娘", zh: "眼镜娘", en: "Glasses", ja: "眼鏡っ娘", tw: "眼鏡娘"),
    HanimeSearchOption(searchKey: "獸耳", zh: "兽耳", en: "Animal Ears", ja: "獣耳", tw: "獸耳"),
    HanimeSearchOption(searchKey: "尖耳朵", zh: "尖耳朵", en: "Pointed Ears", ja: "尖り耳", tw: "尖耳朵"),
    HanimeSearchOption(searchKey: "異色瞳", zh: "异色瞳", en: "Heterochromia", ja: "オッドアイ", tw: "異色瞳"),
    HanimeSearchOption(searchKey: "美人痣", zh: "美人痣", en: "Beauty Mark", ja: "ほくろ", tw: "美人痣"),
    HanimeSearchOption(searchKey: "肌肉女", zh: "肌肉女", en: "Muscle", ja: "筋肉娘", tw: "肌肉女"),
    HanimeSearchOption(searchKey: "白虎", zh: "白虎", en: "Virgin", ja: "パイパン", tw: "白虎"),
    HanimeSearchOption(searchKey: "陰毛", zh: "阴毛", en: "Pubic Stubble", ja: "陰毛", tw: "陰毛"),
    HanimeSearchOption(searchKey: "腋毛", zh: "腋毛", en: "Hairy Armpits", ja: "腋毛", tw: "腋毛"),
    HanimeSearchOption(searchKey: "大屌", zh: "大屌", en: "Big Dick", ja: "巨根", tw: "大屌"),
    HanimeSearchOption(searchKey: "著衣", zh: "穿衣", en: "Clothed", ja: "着衣", tw: "著衣"),
    HanimeSearchOption(searchKey: "水手服", zh: "水手服", en: "Sailor Suit", ja: "セーラー服", tw: "水手服"),
    HanimeSearchOption(searchKey: "體操服", zh: "体操服", en: "Gym Clothes", ja: "体操服", tw: "體操服"),
    HanimeSearchOption(searchKey: "泳裝", zh: "泳装", en: "Swimsuit", ja: "水着", tw: "泳裝"),
    HanimeSearchOption(searchKey: "比基尼", zh: "比基尼", en: "Bikini", ja: "ビキニ", tw: "比基尼"),
    HanimeSearchOption(searchKey: "死庫水", zh: "死库水", en: "School Swimsuit", ja: "スクール水着", tw: "死庫水"),
    HanimeSearchOption(searchKey: "和服", zh: "和服", en: "Kimono", ja: "和服", tw: "和服"),
    HanimeSearchOption(searchKey: "兔女郎", zh: "兔女郎", en: "Bunny Girl", ja: "バニーガール", tw: "兔女郎"),
    HanimeSearchOption(searchKey: "圍裙", zh: "围裙", en: "Apron", ja: "エプロン", tw: "圍裙"),
    HanimeSearchOption(searchKey: "啦啦隊", zh: "啦啦队", en: "Cheerleader", ja: "チアガール", tw: "啦啦隊"),
    HanimeSearchOption(searchKey: "絲襪", zh: "丝袜", en: "Stockings", ja: "ストッキング", tw: "絲襪"),
    HanimeSearchOption(searchKey: "吊襪帶", zh: "吊袜带", en: "Garter Belt", ja: "ガーターベルト", tw: "吊襪帶"),
    HanimeSearchOption(searchKey: "熱褲", zh: "热裤", en: "Hot Pants", ja: "ホットパンツ", tw: "熱褲"),
    HanimeSearchOption(searchKey: "迷你裙", zh: "迷你裙", en: "Mini Skirt", ja: "ミニスカート", tw: "迷你裙"),
    HanimeSearchOption(searchKey: "性感內衣", zh: "性感内衣", en: "Sexy Lingerie", ja: "セクシーランジェリー", tw: "性感內衣"),
    HanimeSearchOption(searchKey: "緊身衣", zh: "紧身衣", en: "Leotard", ja: "ボディスーツ", tw: "緊身衣"),
    HanimeSearchOption(searchKey: "丁字褲", zh: "丁字裤", en: "Thong", ja: "Tバック", tw: "丁字褲"),
    HanimeSearchOption(searchKey: "高跟鞋", zh: "高跟鞋", en: "High Heels", ja: "ハイヒール", tw: "高跟鞋"),
    HanimeSearchOption(searchKey: "睡衣", zh: "睡衣", en: "Nightwear", ja: "パジャマ", tw: "睡衣"),
    HanimeSearchOption(searchKey: "婚紗", zh: "婚纱", en: "Bride", ja: "ウェディングドレス", tw: "婚紗"),
    HanimeSearchOption(searchKey: "旗袍", zh: "旗袍", en: "Cheongsam", ja: "チャイナドレス", tw: "旗袍"),
    HanimeSearchOption(searchKey: "古裝", zh: "古装", en: "Ancient Costume", ja: "時代衣装", tw: "古裝"),
    HanimeSearchOption(searchKey: "哥德", zh: "哥特萝莉塔", en: "Gothic Lolita", ja: "ゴスロリ", tw: "哥德蘿莉塔"),
    HanimeSearchOption(searchKey: "口罩", zh: "口罩", en: "Mouth Mask", ja: "マスク", tw: "口罩"),
    HanimeSearchOption(searchKey: "刺青", zh: "刺青", en: "Tattoo", ja: "タトゥー", tw: "刺青"),
    HanimeSearchOption(searchKey: "淫紋", zh: "淫纹", en: "Sexy Tattoo", ja: "淫紋", tw: "淫紋"),
    HanimeSearchOption(searchKey: "身體寫字", zh: "身体写字", en: "Body Writing", ja: "身体落書き", tw: "身體寫字"),]),
    HanimeTagGroup(id: "story_location", zh: "情景场所", en: "Scenario and Environment", ja: "シチュエーション", tw: "情境場所", options: <HanimeSearchOption>[HanimeSearchOption(searchKey: "校園", zh: "校园", en: "School", ja: "学園", tw: "校園"),
    HanimeSearchOption(searchKey: "教室", zh: "教室", en: "Classroom", ja: "教室", tw: "教室"),
    HanimeSearchOption(searchKey: "圖書館", zh: "图书馆", en: "Library", ja: "図書館", tw: "圖書館"),
    HanimeSearchOption(searchKey: "保健室", zh: "保健室", en: "Health Room", ja: "保健室", tw: "保健室"),
    HanimeSearchOption(searchKey: "游泳池", zh: "游泳池", en: "Swimming Pool", ja: "プール", tw: "游泳池"),
    HanimeSearchOption(searchKey: "愛情賓館", zh: "爱情宾馆", en: "Love Hotel", ja: "ラブホテル", tw: "愛情賓館"),
    HanimeSearchOption(searchKey: "醫院", zh: "医院", en: "Hospital", ja: "病院", tw: "醫院"),
    HanimeSearchOption(searchKey: "辦公室", zh: "办公室", en: "Office", ja: "オフィス", tw: "辦公室"),
    HanimeSearchOption(searchKey: "浴室", zh: "浴室", en: "Bathroom", ja: "浴室", tw: "浴室"),
    HanimeSearchOption(searchKey: "窗邊", zh: "窗边", en: "By the Window", ja: "窓辺", tw: "窗邊"),
    HanimeSearchOption(searchKey: "公共廁所", zh: "公共厕所", en: "Public Toilet", ja: "公衆トイレ", tw: "公共廁所"),
    HanimeSearchOption(searchKey: "公眾場合", zh: "公共场合", en: "Public Place", ja: "公共の場", tw: "公眾場合"),
    HanimeSearchOption(searchKey: "戶外野戰", zh: "户外野战", en: "Outdoor Sex", ja: "野外", tw: "戶外野戰"),
    HanimeSearchOption(searchKey: "電車", zh: "电车", en: "Train", ja: "電車", tw: "電車"),
    HanimeSearchOption(searchKey: "車震", zh: "车震", en: "Car Sex", ja: "カーセックス", tw: "車震"),
    HanimeSearchOption(searchKey: "遊艇", zh: "游艇", en: "Yacht", ja: "ヨット", tw: "遊艇"),
    HanimeSearchOption(searchKey: "露營帳篷", zh: "露营帐篷", en: "Camping Tent", ja: "キャンプテント", tw: "露營帳篷"),
    HanimeSearchOption(searchKey: "電影院", zh: "电影院", en: "Cinema", ja: "映画館", tw: "電影院"),
    HanimeSearchOption(searchKey: "健身房", zh: "健身房", en: "Gym", ja: "ジム", tw: "健身房"),
    HanimeSearchOption(searchKey: "沙灘", zh: "沙滩", en: "Beach", ja: "ビーチ", tw: "沙灘"),
    HanimeSearchOption(searchKey: "溫泉", zh: "温泉", en: "Hot Spring", ja: "温泉", tw: "溫泉"),
    HanimeSearchOption(searchKey: "夜店", zh: "夜店", en: "Nightclub", ja: "ナイトクラブ", tw: "夜店"),
    HanimeSearchOption(searchKey: "監獄", zh: "监狱", en: "Prison", ja: "監獄", tw: "監獄"),
    HanimeSearchOption(searchKey: "教堂", zh: "教堂", en: "Church", ja: "教会", tw: "教堂"),]),
    HanimeTagGroup(id: "story_plot", zh: "故事剧情", en: "Story Plot", ja: "ストーリー", tw: "故事劇情", options: <HanimeSearchOption>[HanimeSearchOption(searchKey: "純愛", zh: "纯爱", en: "Pure Love", ja: "純愛", tw: "純愛"),
    HanimeSearchOption(searchKey: "戀愛喜劇", zh: "恋爱喜剧", en: "Romantic Comedy", ja: "ラブコメ", tw: "戀愛喜劇"),
    HanimeSearchOption(searchKey: "後宮", zh: "后宫", en: "Harem", ja: "ハーレム", tw: "後宮"),
    HanimeSearchOption(searchKey: "十指緊扣", zh: "十指紧扣", en: "Interlocked fingers", ja: "恋人つなぎ", tw: "十指緊扣"),
    HanimeSearchOption(searchKey: "開大車", zh: "开大车", en: "Older Woman Younger Man", ja: "おねショタ", tw: "開大車"),
    HanimeSearchOption(searchKey: "NTR", zh: "NTR", en: "NTR", ja: "NTR", tw: "NTR"),
    HanimeSearchOption(searchKey: "精神控制", zh: "精神控制", en: "Mind Control", ja: "精神支配", tw: "精神控制"),
    HanimeSearchOption(searchKey: "藥物", zh: "药物", en: "Drugs", ja: "薬物", tw: "藥物"),
    HanimeSearchOption(searchKey: "痴漢", zh: "痴汉", en: "Chikan/Molester", ja: "痴漢", tw: "痴漢"),
    HanimeSearchOption(searchKey: "阿嘿顏", zh: "阿嘿颜", en: "Ahegao", ja: "アヘ顔", tw: "阿嘿顏"),
    HanimeSearchOption(searchKey: "精神崩潰", zh: "精神崩溃", en: "Mental Breakdown", ja: "精神崩壊", tw: "精神崩潰"),
    HanimeSearchOption(searchKey: "獵奇", zh: "猎奇", en: "Guro/Gore", ja: "猟奇", tw: "獵奇"),
    HanimeSearchOption(searchKey: "BDSM", zh: "BDSM", en: "BDSM", ja: "BDSM", tw: "BDSM"),
    HanimeSearchOption(searchKey: "綑綁", zh: "捆绑", en: "Bondage", ja: "緊縛", tw: "綑綁"),
    HanimeSearchOption(searchKey: "眼罩", zh: "眼罩", en: "Blindfold", ja: "目隠し", tw: "眼罩"),
    HanimeSearchOption(searchKey: "項圈", zh: "项圈", en: "Collar", ja: "首輪", tw: "項圈"),
    HanimeSearchOption(searchKey: "調教", zh: "调教", en: "Taming/Training", ja: "調教", tw: "調教"),
    HanimeSearchOption(searchKey: "異物插入", zh: "异物插入", en: "Foreign Object Insertion", ja: "異物挿入", tw: "異物插入"),
    HanimeSearchOption(searchKey: "尋歡洞", zh: "寻欢洞", en: "Glory Hole", ja: "グローリーホール", tw: "尋歡洞"),
    HanimeSearchOption(searchKey: "肉便器", zh: "肉便器", en: "Human Toilet", ja: "肉便器", tw: "肉便器"),
    HanimeSearchOption(searchKey: "性奴隸", zh: "性奴隶", en: "Sex Slave", ja: "性奴隷", tw: "性奴隸"),
    HanimeSearchOption(searchKey: "胃凸", zh: "胃凸", en: "Stomach Bulge", ja: "胃凸", tw: "胃凸"),
    HanimeSearchOption(searchKey: "強制", zh: "强制", en: "Forced/Non-Con", ja: "強制", tw: "強制"),
    HanimeSearchOption(searchKey: "輪姦", zh: "轮奸", en: "Gangbang", ja: "輪姦", tw: "輪姦"),
    HanimeSearchOption(searchKey: "凌辱", zh: "凌辱", en: "Humiliation", ja: "凌辱", tw: "凌辱"),
    HanimeSearchOption(searchKey: "性暴力", zh: "性暴力", en: "Sexual Violence", ja: "性暴力", tw: "性暴力"),
    HanimeSearchOption(searchKey: "逆強制", zh: "逆强制", en: "Reverse Non-Con", ja: "逆強制", tw: "逆強制"),
    HanimeSearchOption(searchKey: "女王樣", zh: "女王大人", en: "Queen/Dominatrix", ja: "女王様", tw: "女王樣"),
    HanimeSearchOption(searchKey: "榨精", zh: "榨精", en: "Semen collection", ja: "搾精", tw: "榨精"),
    HanimeSearchOption(searchKey: "母女丼", zh: "母女丼", en: "Mother and Daughter", ja: "母娘丼", tw: "母女丼"),
    HanimeSearchOption(searchKey: "姐妹丼", zh: "姐妹丼", en: "Sisters", ja: "姉妹丼", tw: "姐妹丼"),
    HanimeSearchOption(searchKey: "出軌", zh: "出轨", en: "Cheating/Infidelity", ja: "浮気", tw: "出軌"),
    HanimeSearchOption(searchKey: "醉酒", zh: "醉酒", en: "Drunk", ja: "酔酒", tw: "醉酒"),
    HanimeSearchOption(searchKey: "攝影", zh: "摄影", en: "Filming/Photography", ja: "撮影", tw: "攝影"),
    HanimeSearchOption(searchKey: "睡眠姦", zh: "睡眠奸", en: "Sleep Rape", ja: "睡眠姦", tw: "睡眠姦"),
    HanimeSearchOption(searchKey: "機械姦", zh: "机械奸", en: "Machine Rape", ja: "機械姦", tw: "機械姦"),
    HanimeSearchOption(searchKey: "蟲姦", zh: "虫奸", en: "Insect Rape", ja: "虫姦", tw: "蟲姦"),
    HanimeSearchOption(searchKey: "性轉換", zh: "性转换", en: "Gender Transformation", ja: "性転換", tw: "性轉換"),
    HanimeSearchOption(searchKey: "百合", zh: "百合", en: "Yuri/Lesbian", ja: "百合", tw: "百合"),
    HanimeSearchOption(searchKey: "耽美", zh: "耽美", en: "BL/Yaoi", ja: "BL", tw: "耽美"),
    HanimeSearchOption(searchKey: "時間停止", zh: "时间停止", en: "Time Stop", ja: "時間停止", tw: "時間停止"),
    HanimeSearchOption(searchKey: "異世界", zh: "异世界", en: "Isekai", ja: "異世界", tw: "異世界"),
    HanimeSearchOption(searchKey: "怪獸", zh: "怪兽", en: "Monster", ja: "怪獣", tw: "怪獸"),
    HanimeSearchOption(searchKey: "哥布林", zh: "哥布林", en: "Goblin", ja: "ゴブリン", tw: "哥布林"),
    HanimeSearchOption(searchKey: "世界末日", zh: "世界末日", en: "Apocalypse", ja: "世界末日", tw: "世界末日"),]),
    HanimeTagGroup(id: "sex_positions", zh: "性交体位", en: "Sex Positions", ja: "性交体位", tw: "性交體位", options: <HanimeSearchOption>[HanimeSearchOption(searchKey: "手交", zh: "手交", en: "Handjob", ja: "手コキ", tw: "手交"),
    HanimeSearchOption(searchKey: "指交", zh: "指交", en: "Fingering", ja: "指入れ", tw: "指交"),
    HanimeSearchOption(searchKey: "乳交", zh: "乳交", en: "Titty fuck", ja: "パイズリ", tw: "乳交"),
    HanimeSearchOption(searchKey: "乳頭交", zh: "乳头交", en: "Nipple Stimulation", ja: "乳首責め", tw: "乳頭交"),
    HanimeSearchOption(searchKey: "肛交", zh: "肛交", en: "Anal Sex", ja: "アナル", tw: "肛交"),
    HanimeSearchOption(searchKey: "雙洞齊下", zh: "双洞齐下", en: "Double Penetration", ja: "二穴責め", tw: "雙洞齊下"),
    HanimeSearchOption(searchKey: "腳交", zh: "足交", en: "Footjob", ja: "足コキ", tw: "腳交"),
    HanimeSearchOption(searchKey: "素股", zh: "素股", en: "Sumata/Thigh Sex", ja: "素股", tw: "素股"),
    HanimeSearchOption(searchKey: "拳交", zh: "拳交", en: "Fisting", ja: "フィスト", tw: "拳交"),
    HanimeSearchOption(searchKey: "3P", zh: "3P", en: "3P", ja: "3P", tw: "3P"),
    HanimeSearchOption(searchKey: "群交", zh: "群交", en: "Orgy", ja: "乱交", tw: "群交"),
    HanimeSearchOption(searchKey: "口交", zh: "口交", en: "Oral Sex", ja: "フェラ", tw: "口交"),
    HanimeSearchOption(searchKey: "跪舔", zh: "跪舔", en: "Grovel", ja: "跪き舐め", tw: "跪舔"),
    HanimeSearchOption(searchKey: "深喉嚨", zh: "深喉", en: "Deepthroat", ja: "ディープスロート", tw: "深喉嚨"),
    HanimeSearchOption(searchKey: "口爆", zh: "口爆", en: "Cum in Mouth", ja: "口内射精", tw: "口爆"),
    HanimeSearchOption(searchKey: "吞精", zh: "吞精", en: "Swallowing Cum", ja: "ごっくん", tw: "吞精"),
    HanimeSearchOption(searchKey: "舔蛋蛋", zh: "舔蛋蛋", en: "Ball Licking", ja: "睾丸舐め", tw: "舔蛋蛋"),
    HanimeSearchOption(searchKey: "舔穴", zh: "舔穴", en: "Pussy Licking", ja: "クンニ", tw: "舔穴"),
    HanimeSearchOption(searchKey: "69", zh: "69", en: "69", ja: "69", tw: "69"),
    HanimeSearchOption(searchKey: "自慰", zh: "自慰", en: "Masturbation", ja: "オナニー", tw: "自慰"),
    HanimeSearchOption(searchKey: "腋交", zh: "腋交", en: "Armpit Sex", ja: "腋コキ", tw: "腋交"),
    HanimeSearchOption(searchKey: "舔腋下", zh: "舔腋下", en: "Armpit Licking", ja: "腋舐め", tw: "舔腋下"),
    HanimeSearchOption(searchKey: "髮交", zh: "发交", en: "Hair Sex", ja: "髪コキ", tw: "髮交"),
    HanimeSearchOption(searchKey: "舔耳朵", zh: "舔耳朵", en: "Ear Licking", ja: "耳舐め", tw: "舔耳朵"),
    HanimeSearchOption(searchKey: "舔腳", zh: "舔脚", en: "Feet Licking", ja: "足舐め", tw: "舔腳"),
    HanimeSearchOption(searchKey: "內射", zh: "内射", en: "Internal Ejaculation", ja: "中出し", tw: "內射"),
    HanimeSearchOption(searchKey: "外射", zh: "外射", en: "External Ejaculation", ja: "外出し", tw: "外射"),
    HanimeSearchOption(searchKey: "顏射", zh: "顏射", en: "Facial", ja: "顔射", tw: "顏射"),
    HanimeSearchOption(searchKey: "潮吹", zh: "潮吹", en: "Squirting", ja: "潮吹き", tw: "潮吹"),
    HanimeSearchOption(searchKey: "懷孕", zh: "怀孕", en: "Pregnancy", ja: "妊娠", tw: "懷孕"),
    HanimeSearchOption(searchKey: "噴奶", zh: "喷奶", en: "Lactation", ja: "母乳", tw: "噴奶"),
    HanimeSearchOption(searchKey: "放尿", zh: "放尿", en: "Urinating", ja: "放尿", tw: "放尿"),
    HanimeSearchOption(searchKey: "排便", zh: "排便", en: "Defecation", ja: "排便", tw: "排便"),
    HanimeSearchOption(searchKey: "騎乘位", zh: "骑乘位", en: "Riding Position", ja: "騎乗位", tw: "騎乘位"),
    HanimeSearchOption(searchKey: "背後位", zh: "背后位", en: "Doggy Style", ja: "バック", tw: "背後位"),
    HanimeSearchOption(searchKey: "顏面騎乘", zh: "颜面骑乘", en: "Facesitting", ja: "顔面騎乗", tw: "顏面騎乘"),
    HanimeSearchOption(searchKey: "火車便當", zh: "火车便当", en: "Tate Dama", ja: "駅弁", tw: "火車便當"),
    HanimeSearchOption(searchKey: "一字馬", zh: "一字马", en: "Do the splits", ja: "開脚", tw: "一字馬"),
    HanimeSearchOption(searchKey: "性玩具", zh: "性玩具", en: "Sex Toys", ja: "性玩具", tw: "性玩具"),
    HanimeSearchOption(searchKey: "飛機杯", zh: "飞机杯", en: "Onahole", ja: "オナホ", tw: "飛機杯"),
    HanimeSearchOption(searchKey: "跳蛋", zh: "跳蛋", en: "Vibrating Egg", ja: "ローター", tw: "跳蛋"),
    HanimeSearchOption(searchKey: "毒龍鑽", zh: "毒龙钻", en: "Rimjob", ja: "ドリル責め", tw: "毒龍鑽"),
    HanimeSearchOption(searchKey: "觸手", zh: "触手", en: "Tentacles", ja: "触手", tw: "觸手"),
    HanimeSearchOption(searchKey: "獸交", zh: "兽交", en: "Bestiality", ja: "獣姦", tw: "獸交"),
    HanimeSearchOption(searchKey: "頸手枷", zh: "颈手枷", en: "Stocks", ja: "首手枷", tw: "頸手枷"),
    HanimeSearchOption(searchKey: "扯頭髮", zh: "扯头发", en: "Hair pulling", ja: "髪引っ張り", tw: "扯頭髮"),
    HanimeSearchOption(searchKey: "掐脖子", zh: "掐脖子", en: "Choking", ja: "首絞め", tw: "掐脖子"),
    HanimeSearchOption(searchKey: "打屁股", zh: "打屁股", en: "Spanking", ja: "スパンキング", tw: "打屁股"),
    HanimeSearchOption(searchKey: "肉棒打臉", zh: "肉棒打脸", en: "Cock Slap", ja: "肉棒ビンタ", tw: "肉棒打臉"),
    HanimeSearchOption(searchKey: "陰道外翻", zh: "阴道外翻", en: "Vaginal Eversion", ja: "膣外反", tw: "陰道外翻"),
    HanimeSearchOption(searchKey: "男乳首責", zh: "男乳首责", en: "Male tit torture", ja: "男乳首責め", tw: "男乳首責"),
    HanimeSearchOption(searchKey: "接吻", zh: "接吻", en: "Kissing", ja: "キス", tw: "接吻"),
    HanimeSearchOption(searchKey: "舌吻", zh: "舌吻", en: "French Kissing", ja: "ディープキス", tw: "舌吻"),
    HanimeSearchOption(searchKey: "POV", zh: "POV", en: "POV", ja: "POV", tw: "POV"),]),];

/// 按应用语言码返回筛选选项显示名：zh*/zh_Hans*→简体，zh_Hant*/zh-TW→繁体，en*→英文，ja*→日文，其余兜底简体。
String hanimeSearchOptionDisplayName(
  HanimeSearchOption option,
  String localeCode,
) {
  return _hanimeLocaleDisplayName(
    localeCode: localeCode,
    zh: option.zh,
    en: option.en,
    ja: option.ja,
    tw: option.tw,
  );
}

/// 按应用语言码返回标签分组显示名，规则同 hanimeSearchOptionDisplayName。
String hanimeTagGroupDisplayName(HanimeTagGroup group, String localeCode) {
  return _hanimeLocaleDisplayName(
    localeCode: localeCode,
    zh: group.zh,
    en: group.en,
    ja: group.ja,
    tw: group.tw,
  );
}

String _hanimeLocaleDisplayName({
  required String localeCode,
  required String zh,
  required String en,
  required String ja,
  required String tw,
}) {
  final lower = localeCode.toLowerCase();
  if (lower.startsWith('zh') &&
      (lower.contains('hant') || lower.contains('-tw') ||
          lower.contains('_tw'))) {
    return tw;
  }
  if (lower.startsWith('zh')) return zh;
  if (lower.startsWith('en')) return en;
  if (lower.startsWith('ja')) return ja;
  return zh;
}
// dart format on
